version: '3.5'
services:

  mongo1:
    hostname: localhost
    container_name: localmongo1
    image: mongo:5.0
    expose:
      - 27017
    ports:
      - 30001:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - mongo1